#!/bin/sh
#
# Copyright (C) 2006 ircd-ratbox development team
# This code is in the public domain.

set -e

KEYNAME=${1:-$USER}

echo 'WARNING: openssl does not allow using a secure key-from-passphrase
derivation function such as pbkdf2 to protect the private key. you should
use a long random password, such as one from a password manager, or treat
it as unencrypted.'

openssl genrsa -out "$KEYNAME.sec" -aes-256-cfb 4096

echo "Generating RSA public key..."
openssl rsa -in "$KEYNAME.sec" -out "$KEYNAME.pub" -pubout
